services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/imagegallery
      - PEXELS_API_KEY=${PEXELS_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

